### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by fury02** [ssrlive/rust_on_android#1]
I installed everything and can't build it in Ubuntu 20.04

linking with `/home/fury/OtherProjects/Android/rust_on_android-main/platform/android/build/linker-wrapper/linker-wrapper.sh` failed: exit status: 127

Execution failed for task ':app:cargoBuildArm64'.
Process 'command 'cargo'' finished with non-zero exit value 101

**Comment by fury02** [comment]
Everything is so. I think the problem with linker-wrapper.py . It doesn't always work. Maybe not. I'm checking.

**Comment by ssrlive** [comment]
resolve for android-ndk-r23

https://github.com/Ar37-rs/ndk-r23-fix-for-rust

target path in linux is `~/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc`

**Comment by ssrlive** [comment]
#### Fixing build error for Above NDK 23 and above

find out all the 4 folders containing file `libunwind.a`, in my PC, it's `C:\Users\Administrator\AppData\Local\Android\Sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\12.0.8\lib\linux\x86_64\` and more.
create 4 `text` files named `libgcc.a` in the same folders with this contents
```
INPUT(-lunwind)
```

![image](https://user-images.githubusercontent.com/30760636/153782719-458e0054-a800-4a62-87b7-c3fa80a7008c.png)

[reference link](https://github.com/rust-windowing/android-ndk-rs/pull/189/files#diff-9c2f0d812ce52310e2784d3ba203437e6f318230e4e4f701b321a0f656dfa416R180-R187)

**Comment by github-user001** [comment]
> Ok.
> This should work if you add
> local.properties
> ndk.dir=/home/********/Android/Sdk/ndk/22.1.7171670

I had to add that version of the NDK I was using to the `app/build.gradle` as well.

**Comment by ssrlive** [comment]
If you follow this tips, error will be fixed indeed. @github-user001 

> #### Fixing build error for Above NDK 23 and above
> find out all the 4 folders containing file `libunwind.a`, in my PC, it's 
> ...
